spring.application.name=DemoFuryServer

#http server port
server.port=8081

#Fury Starter
#springboot.fury.treadSafeFury=true
springboot.fury.treadSafeFuryPool=true
springboot.fury.minTreadSafeFuryPool=1
springboot.fury.maxTreadSafeFuryPool=10
springboot.fury.scanPackages=org.heg
