spring.application.name=DemoFuryServer

#http server port
server.port=8081

#Fury Starter
springboot.fury.treadSafeFuryPool=true
springboot.fury.minTreadSafeFuryPool=2
springboot.fury.maxTreadSafeFuryPool=10
springboot.fury.scanPackages=org.heg
